package com.wonder.v5.common.enumeration.game;

import lombok.Getter;

@Getter
public enum PlatformEnum {

  PLATFORM_BBIN(2, "BBIN"),
  PLATFORM_DG(3, "DG"),
  PLATFORM_AG(4, "AG"),
  PLATFORM_KY(5, "KY"),
  PLATFORM_LEG(6, "LEG"),
  PLATFORM_CQ9(7, "CQ9"),
  PLATFORM_AB(9, "AB"),
  PLATFORM_CMD(10, "CMD"),
  PLATFORM_BG(11, "BG"),
  PLATFORM_OG_PLUS(12, "OG_PLUS"),
  PLATFORM_VG(13, "VG"),
  PLATFORM_SABA(14, "SABA"),
  PLATFORM_JDB(15, "JDB"),
  PLATFORM_MG(16, "MG"),
  PLATFORM_FG(17, "FG"),
  PLATFORM_TCG(19, "TCG"),
  PLATFORM_SA(20, "SA"),
  PLATFORM_AE(21, "AE"),
  PLATFORM_BTI(22, "BTI"),
  PLATFORM_GW(23, "GW"),
  PLATFORM_PG(24, "PG"),
  PLATFORM_JOKER(25, "JOKER"),
  PLATFORM_SEXY(26, "SEXY"),
  PLATFORM_HC(27, "HC"),
  PLATFORM_KM(28, "KM"),
  PLATFORM_S128(30, "S128"),
  PLATFORM_XG(31, "XG"),
  PLATFORM_JQ(32, "JQ"),
  PLATFORM_CR(33, "CR"),
  PLATFORM_OB(34, "OB"),
  PLATFORM_AVIA(36, "AVIA"),
  PLATFORM_SEXY_SPORT(37, "SEXYSPORT"),
  PLATFORM_WM(38, "WM"),
  PLATFORM_KS(40, "KS"),
  PLATFORM_FB(42, "FB"),
  PLATFORM_V8(43, "V8"),
  PLATFORM_MP(44, "MP"),
  PLATFORM_REEVO(45, "REEVO"),
  PLATFORM_POLY(46, "POLY"),
  PLATFORM_BL(47, "BL"),
  PLATFORM_CB(48, "CB"),
  PLATFORM_PP(49, "PP"),
  PLATFORM_EVO(50, "EVO"),
  PLATFORM_OBLIVE(51, "OBLIVE"),
  PLATFORM_PNG(52, "PNG"),
  PLATFORM_JILI(53, "JILI"),
  PLATFORM_T1(54, "T1"),
  PLATFORM_WALI(55, "WALI"),
  PLATFORM_JQ_LOTTERY(56, "JQLOTTERY"),
  PLATFORM_MGP(57, "MGP"),
  PLATFORM_FC(58, "FC"),
  PLATFORM_ROYAL_LIVE(59, "ROYALLIVE"),
  PLATFORM_ROYAL_SLOT(60, "ROYALSLOT"),
  PLATFORM_DS88(61, "DS88"),
  PLATFORM_RICH88(62, "RICH88"),
  PLATFORM_UG(63, "UG"),
  PLATFORM_WE(64, "WE"),
  PLATFORM_CBVN(65, "CBVN"),
  PLATFORM_KA(66, "KA"),
  PLATFORM_TCGSEA(67, "TCGSEA"),
  PLATFORM_9WICKETS(68, "9WICKETS"),
  PLATFORM_SPADEGAMING(69, "SPADEGAMING"),
  PLATFORM_WGB(70, "WGB"),
  PLATFORM_TCGVN(71, "TCGVN"),
  PLATFORM_FUNKYGAME(72, "FUNKYGAME"),
  PLATFORM_IM(73, "IM"),
  PLATFORM_IMESPORT(74, "IMESPORT"),
  PLATFORM_HORSEBOOK(75, "HORSEBOOK"),
  PLATFORM_SBO(76, "SBO"),
  PLATFORM_PMLOTTERY(77, "PMLOTTERY"),
  PLATFORM_TP(78, "TP"),
  PLATFORM_VR(79, "VR"),
  PLATFORM_WS168(80, "WS168"),
  PLATFORM_MW(81, "MW"),
  PLATFORM_TF(82, "TF"),
  PLATFORM_PINNACLE(83, "PINNACLE"),
  PLATFORM_RELAXGAMING(84, "RELAXGAMING"),
  PLATFORM_WINFAST(85, "WINFAST"),
  PLATFORM_CG(86, "CG"),
  PLATFORM_DAYWIN_FUNKY(720001, "DAYWINFUNKY"),
  PLATFORM_LUCKY_SPORTS(87, "LUCKYSPORTS"),
  PLATFORM_SGWIN(88, "SGWIN"),
  PLATFORM_SPRIBE(89,"SPRIBE"),
  PLATFORM_AFB_LIVE(90,"AFBLIVE"),
  PLATFORM_AFB_SPORT(91,"AFBSPORT"),
  PLATFORM_AFB_GAME(92,"AFBGAME"),
  PLATFORM_ALIZE(94, "ALIZE"),
  PLATFORM_HB(95,"HB"),
  PLATFORM_HUAWEI(96,"HUAWEI"),
  PLATFORM_FV(97,"FV"),
  PLATFORM_RED_TIGER(98, "REDTIGER"),
  PLATFORM_BIG_TIME(99, "BIGTIME"),
  PLATFORM_NETENT(100, "NETENT"),
  PLATFORM_NO_LIMIT_CITY(101, "NOLIMITCITY"),
  PLATFORM_PGPLUS(102, "PGPLUS"),
  PLATFORM_28WIN(103, "28WIN"),
  PLATFORM_3SING(104, "3SING"),
  PLATFORM_TADA(105, "TADA"),
  PLATFORM_PLAY_TECH(106, "PLAYTECH"),
  PLATFORM_CRICKET_BOOK(107, "CRICKETBOOK"),
  PLATFORM_INDIGAMES(108, "INDIGAMES"),
  PLATFORM_EZUGI(109, "EZUGI"),
  PLATFORM_DV(110, "DV"),
  PLATFORM_EVOPLAY(111, "EVOPLAY"),
  PLATFORM_YGG(112, "YGG"),
  PLATFORM_INDIA_LOTTERY(113, "INDIALOTTERY"),
  PLATFORM_SV388(114, "SV388"),
  PLATFORM_XE88(115, "XE88"),
  PLATFORM_LIVE22(116, "LIVE22"),
  PLATFORM_FUNTA(117, "FUNTA"),
  PLATFORM_IA(118, "IA"),
  PLATFORM_WBET(119, "WBET"),
  PLATFORM_LUCKY365(120, "LUCKY365"),
  PLATFORM_UUSLOT(121, "UUSLOT"),
  PLATFORM_VPOWER(122, "VPOWER"),
  PLATFORM_3SINGHK(123, "3SINGHK"),
  PLATFORM_BAISON(124, "BAISON"),
  PLATFORM_ASTAR(125, "ASTAR"),
  PLATFORM_MAHA(126, "MAHA"),
  PLATFORM_SABONG(127, "SABONG"),
  PLATFORM_AWC_PG(128, "AWCPG"),
  PLATFORM_HUAWEI88(129, "HUAWEI88"),
  PLATFORM_YINBO(130, "YINBO"),
  PLATFORM_WS_SPORT(131, "WSSPORT"),
  PLATFORM_OMG_JILI(135, "OMGJILI"),
  PLATFORM_OMG_PP(136, "OMGPP"),
  PLATFORM_OMG_PG(137, "OMGPG"),
  PLATFORM_OMG_SPRIBE(140, "OMGSPRIBE"),
  PLATFORM_OMG_HACKSAW(141, "OMGHACKSAW"),
  PLATFORM_OMG(142, "OMG"),
  PLATFORM_DBESPORT(143, "DBESPORT"),
  PLATFORM_FB_LIVE(144, "FBLIVE"),
  PLATFORM_FUNIBETKY(145, "FUNIBETKY"),
  PLATFORM_FUNIBETTY(146, "FUNIBETTY"),
  PLATFORM_BTGAMING(147, "BTGAMING"),
  PLATFORM_GFG(148, "GFG"),
  PLATFORM_GLC(149, "GLC"),
  PLATFORM_VIA(150, "VIA"),
  PLATFORM_COD(151, "COD"),
  PLATFORM_ONLIVE(152, "ONLIVE"),
  PLATFORM_BNG(153, "BNG"),
  PLATFORM_YEEBET(154, "YEEBET"),
  PLATFORM_ONEEVO(156, "ONEEVO"),
  PLATFORM_VA(157, "VA"),
  PLATFORM_NEXTSPIN(158, "NEXTSPIN"),
  PLATFORM_ATG(159, "ATG"),
  PLATFORM_MT(161, "MT"),
  PLATFORM_YB(162, "YB"),
  PLATFORM_SPLUS(163, "SPLUS"),
  PLATFORM_LM(127001, "LM"),
  PLATFORM_CR271(66271001, "CR271"),
  PLATFORM_FL261(66261001, "FL261");

  /**
   * id 需和 DB: platform_main_info 資料一致
   */
  
  private int id;
  private String text;
  
  private static final PlatformEnum[] CACHE;
  static {
    CACHE = PlatformEnum.values();
  }

  PlatformEnum(int id, String text) {
    this.id = id;
    this.text = text;
  }

  public static PlatformEnum valueById(Integer id) {
    if (id == null) {
      return null;
    }

    for (var value : CACHE) {
      if (value.getId() == id) {
        return value;
      }
    }
    return null;
  }

  public static PlatformEnum valueByPrefix(String text) {
    if (text == null) {
      return null;
    }

    for (var value : CACHE) {
      if (value.getText().equals(text)) {
        return value;
      }
    }
    return null;
  }

}
